### ISSUE TITLE
Not Organzing past m9

### ISSUE THREAD

**Issue by Paranti** [AkinAguda/youtubedl-pluralsight-sorter#1]
Great script, although for some reason with the course I'm trying to sort, it's not running past m9.

**Comment by AkinAguda** [comment]
Thanks for the observation. This issue has been fixed in [this](https://github.com/AkinAguda/youtubedl-pluralsight-sorter/commit/15a992e33197fdd54bc6ebcebe4dda6d609f00ed) commit.
